### PR TITLE
Reduction of margins on small screens, prior like/rt condition applied

### PR DESCRIPTION
**Pull request by RobertAndion**

### CODE REVIEW

**Comment by thomasbiv** [comment]
Looks good, but I do have one question. Is the code that handles the like and retweet condition using inverse logic?

Ex.
`props.tweet.user_retweet === 'True' ? setRetweetEnabled(false) : setRetweetEnabled(true); `

Should the logic here be switched for simplicity?

**Review by thomasbiv — COMMENTED** [review]
Looks good, but I do have one question. Is the code that handles the like and retweet condition using inverse logic?

Ex.
`props.tweet.user_retweet === 'True' ? setRetweetEnabled(false) : setRetweetEnabled(true); `

Should the logic here be switched for simplicity?

**Comment by RobertAndion** [comment]
The function is an enable switch so if it has been previously liked or retweeted it is labeled true and then the switch should go to false. The logic is opposite by nature, does this make more sense?

**Comment by thomasbiv** [comment]
> The function is an enable switch so if it has been previously liked or retweeted it is labeled true and then the switch should go to false. The logic is opposite by nature, does this make more sense?

That does, thanks!

**Review by saumyabhadani95 — APPROVED** [review]

**Pull request merged**
