### PR TITLE
Attention check is completed

### PR DESCRIPTION
**Pull request by saumyabhadani95**
The buttons of the attention check should work now, and they are also centered. Also the bug regarding the two unseen tweets should also be fixed (#114). Please review

### CODE REVIEW

**Review by thomasbiv — APPROVED** [review]

**Review by RobertAndion — COMMENTED** [review]
What is the tweetids.txt file doing? is this something that should be on the git ignore or is it needed?

**Comment by saumyabhadani95** [comment]
@RobertAndion that file is not important. I was using it to debug. Have deleted it now. Thanks for catching it!!

**Comment by RobertAndion** [comment]
I approve this for merging however it seems you will have to fix some merge conflicts first @saumyabhadani95

**Comment by glciampaglia** [comment]
I'm getting some errors in react that seem related to the attention check:
```
Failed to compile.

src/components/AttentionCheck/MainAttentionPage.js
  Line 43:7:   'attn_marked' is not defined            no-undef
  Line 45:7:   'attn_marked' is not defined            no-undef
  Line 47:25:  'attn_marked' is not defined            no-undef
  Line 48:11:  'attn_marked' is not defined            no-undef
  Line 54:7:   'setEndOfFeedCondition' is not defined  no-undef
  Line 58:5:   'tweet_pos' is not defined              no-undef
  Line 58:17:  'tweet_pos' is not defined              no-undef
  Line 64:7:   'attn_marked' is not defined            no-undef
  Line 66:7:   'attn_marked' is not defined            no-undef
  Line 68:25:  'attn_marked' is not defined            no-undef
  Line 69:11:  'attn_marked' is not defined            no-undef
  Line 75:7:   'setEndOfFeedCondition' is not defined  no-undef

Search for the keywords to learn more about each error.
```

**Comment by saumyabhadani95** [comment]
It should be fixed now in the main branch. I made some mistakes while resolving the merge conflicts. Sorry:/

**Comment by glciampaglia** [comment]
It works now. Thanks!

**Pull request merged**
