### PR TITLE
LongText issue

### LINKED ISSUE #140: Long text
In one tweet, the text was super long. Obviously much longer than the max. tweet length. It seems that the tweet had a link to an article and the full text of the article was included, instead of just a short preview. 

I searched on Twitter and found the tweet: https://twitter.com/jljcolorado/status/1482375110354870276

Here is the linked article: https://www.mcgill.ca/oss/article/covid-19/covid-19-air-both-problem-and-solution

You can see the reason of the problem: the article itself has the `<meta property="og:description" content="...">` and `<meta name="description" content="...">` metadata fields containing the full text of the article. 

This may not be a big problem but the behavior differs from Twitter, which truncates the preview...

### PR DESCRIPTION
**Pull request by 1449Antonio**
This pull request should now serve to fully solve the long text issue. Anytime we detect a description or title that is over a certain length, we will truncate it and add "..." to it. The numbers can be adjusted as needed in the future.

Should resolve #140

### CODE REVIEW

**Review by glciampaglia — CHANGES_REQUESTED** [review]
No magic numbers please! [1] Either define a global variable at the beginning of the module or, better yet, add an extra entry to the configuration file.

[1] https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad

**Comment by 1449Antonio** [comment]
Please remember to edit the config.ini file with the new additions in the config.sample.ini file

**Review by glciampaglia — APPROVED** [review]

**Comment by thomasbiv** [comment]
I am again getting error code 1 as soon as main feed is supposed to load in, which appears to be linked to an error fetching the tweets from Twitter.
error code 1
.

**Review by thomasbiv — APPROVED** [review]

**Review by saumyabhadani95 — APPROVED** [review]

**Review by RobertAndion — APPROVED** [review]
Excellent changes, the addition of the config file parameter has made it clearly legible and the removal of redundant code looks great.

**Pull request merged**
